services:
  secure_file_upload:
    build: .
    container_name: secure_file_upload_app
    ports:
      - "8084:8084"
    volumes:
      - ./uploads:/app/uploads
      - ./db:/app/db
    env_file:
      - .env
    restart: unless-stopped
